### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Anton-Latukha** [Anton-Latukha/haskell-with-nixpkgs#12]
- [ ] Choose the name
- [ ] Add Cachix cache
  - [ ] Get the Cachix secret
    - [ ] Register Cachix profile
- [ ] Documentation
  - [ ] Gather comments into the doc
- [ ] Make project setup as a submodule, use a branch with autorebase
- [ ] Add Static executable build
  - [ ] Add Complettioins test
  - [ ] Add Executable
